#!/bin/sh

echo ""

echo -n "running autoheader..."
autoheader --force
echo "done"

echo -n "running libtoolize..."
libtoolize --force --copy --automake
echo "done"

echo -n "running aclocal..."
aclocal --force -I m4
echo "done"

echo -n "running autoconf..."
autoconf --force
echo "done"

echo -n "running autoheader..."
autoheader --force
echo "done"

echo -n "running automake..."
automake --force-missing --copy
echo "done"

echo ""
